### PR TITLE
Add Travis CI config file (#10)

### PR DESCRIPTION
**Pull request by nleiva**
Drafting a Travis CI config file. This only starts to make sense after (#13) is merged as it adds test cases.

- [x] Add test cases to code base. (#13) can get us started.
- [x] Add `nornir-automation/gornir` to [Travis CI](https://travis-ci.com/).
- [x] Add `nornir-automation/gornir` to [Codev](https://codecov.io) for test coverage badge.
- [x] Create `.travis.yml` file.
- [x] Add Readme badge.
- [x] Add Go Report card.

### CODE REVIEW

**Comment by dbarrosop** [comment]
I usually prefer using containers and a Makefile for this instead as then you have the same environment both locally and in the CI. I will open an alternative to this PR later today and we can discuss when we have them side by side.

**Comment by dbarrosop** [comment]
Check #14 and let me know what you think, I personally prefer to run everything in containers so the environment is 100% the same everywhere.

**Comment by nleiva** [comment]
> Check #14 and let me know what you think, I personally prefer to run everything in containers so the environment is 100% the same everywhere.

I think that's preferred for languages like Python, I don't think we really need it for Go. I'd recommend we stick to what is more common out there, but again this is more of a personal preference.

- [Logrus](https://github.com/sirupsen/logrus/blob/master/.travis.yml)
- [Dgraph](https://github.com/dgraph-io/dgraph/blob/master/.travis.yml)
- [Hugo](https://github.com/gohugoio/hugo/blob/master/.travis.yml)
- [Prometheus](https://github.com/prometheus/prometheus/blob/master/.travis.yml)

**Comment by dbarrosop** [comment]
Should we merge? We can add what's missing in other PRs.

**Comment by dbarrosop** [comment]
Added codecov https://codecov.io/gh/nornir-automation/gornir

**Comment by nleiva** [comment]
Yeah, I think we are ready.

**Pull request merged**
