### PR TITLE
remove vendor folder

### PR DESCRIPTION
**Pull request by dbarrosop**
To merge after #21

### CODE REVIEW

**Comment by dbarrosop** [comment]
Done

**Comment by nleiva** [comment]
One more thing, so it can build with Go1.12, we need to add `GO111MODULE=on`. Also, it using a Go module proxy will speed up things: `GOPROXY=https://proxy.golang.org`. Below the changes required:

```
services:
    gornir:
        image: golang:1.12-stretch
        ...
        environment:
            - GO111MODULE=on
            - GOPROXY=https://proxy.golang.org
```

**Comment by dbarrosop** [comment]
Added the env variables as requested

**Comment by nleiva** [comment]
Thanks, this looks good to me. It should build using Go modules now.

**Pull request merged**
