### PR TITLE
decoupled connections and task

### PR DESCRIPTION
**Pull request by Ali-aqrabawi**
created a new pkg connection which is similar to `nornir` connections,
this is related to #3

### CODE REVIEW

**Comment by dbarrosop** [comment]
Thanks for the PR. However, this is not what I had in mind. A few general comments:

1. The interface defined is good for command based interactions like ssh and telnet but it's not going to work for rest/restconf/netconf/grpc. In any case, the interface probably just needs the open/close methods and the rest will be up to type casting.
2. The idea with handling connections is to be able to reuse the sessions across different tasks, for instance, you could connect via ssh, upload a file via sftp/scp, send a command and close the connection.

Give some time to work on a proposal for this and then we can add the gomiko connection plugin and reference tasks.

**Comment by Ali-aqrabawi** [comment]
the send `Send` method takes an `interface` which can be `string`, `xml` or `json`, so it should work with different types, and the `casting/typeAssertion` done inside the `implementation`, 

the `SSHCon` has `*ssh.Session` property which maintain the session for multiple `Run` Commands as well as in `gomiko`.

does that make sense?

**Comment by dbarrosop** [comment]
> and the casting/typeAssertion done inside the implementation

That means that `Send` might do different things on the same plugin depending on the arguments, which is confusing and hard to test. It also means the connection plugin is hardwired so it's harder to extend and becomes more complex to develop and maintain. It's easier/cleaner if you keep the connection plugin lean and delegate the responsibility of what to do with the session to the task.

> which maintain the session for multiple Run Commands

With your implementation that's true for a single grouped task.

Let me mock something very quickly and we can take the discussion from there.

**Comment by Ali-aqrabawi** [comment]
> That means that Send might do different things
>
not really, its the same thing but different `implementation` one send a command string, other send a command `xml`, 
same apply for `open` and `close`, one does `ssh` `auth` and other does `https OAuth` or something else, 
so basically  it's same `job` different `implementation/protocol`.

>With your implementation that's true for a single grouped task.
>
not sure about this, the implementation is exactly the same as in `nornir`,is multiple grouped tasks supported by `nornir`?

**Comment by dbarrosop** [comment]
> one send a command string, other send a command xml

There is more you may want to do over a transport protocol, sending files, subscribe to events, etc. And it doesn't work well (or at all) with grpc.

> not sure about this, the implementation is exactly the same as in nornir,is multiple grouped tasks supported by nornir?

The implementation doesn't look much like nornir, for instance, nornir doesn't implement the `Send` method precisely for the reasons stated above.

> is multiple grouped tasks supported by nornir

Yes

**Comment by Ali-aqrabawi** [comment]
>The implementation doesn't look much like nornir, for instance, nornir doesn't implement the Send method precisely for the reasons stated above.
>
i mean for sending multiple commands on same connection, `nornir` have a connection plugging for paramiko and netmiko, the `open` connect to the device and maintain the connection to be used later, which is exactly the same in the `pr`, i open a session and store it in `*ssh.Session` attribute of the `SSHConn`, 
`send` method just uses the connection that was created by the `open`,

**Comment by dbarrosop** [comment]
Ok, we are probably talking about different things. My main concern is being able to reuse the connection. I already opened #37 which should be enough to illustrate what I mean.

**Comment by Ali-aqrabawi** [comment]
an `pr` will be made after #37 is merged.

**Pull request closed without merging**
