### PR TITLE
Test examples

### LINKED ISSUE #19: test examples
test examples somehow

### PR DESCRIPTION
**Pull request by dbarrosop**
Fixes #19 

We will have to add to travis as well when we merge that one.

### CODE REVIEW

**Comment by nleiva** [comment]
I would simplify `lint` and only use containers for testing the examples. So, something like:

```yaml
lint:
	golangci-lint run
```

Instead of:

```yaml
lint:
	docker run \
		--rm \
		-v $(PWD):/go/src/$(PROJECT) \
		-w /go/src/$(PROJECT) \
		golangci/golangci-lint \
			golangci-lint run
```

**Comment by dbarrosop** [comment]
There is another PR somewhere (what a mess, need to start merging these and rebasing) where the version is pinned, otherwise you run into issues where nothing changes but a new version adds a new check and things start failing. Go modules doesn't support yet binaries so unless we vendor it this is the best we can do (to the best of my knowledge)

**Comment by nleiva** [comment]
What about something like this, where we stick to a particular release of golint (`1.17.0` in the example)?. I haven't tested it, but this is how I just installed here in my laptop.

```
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.0
golangci-lint run
```

or maybe:

```
GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.17.0
golangci-lint run
```

**Comment by dbarrosop** [comment]
That works until you need to work in multiple projects and they use different binaries. It's the reason why some people want to expand go modules to binaries.

Is there anything in particular that concerns you about using docker for a use case like this?

**Comment by nleiva** [comment]
No concern other than keeping things as simple as possible.

Running the [golangci/golangci-lint](https://hub.docker.com/r/golangci/golangci-lint) is equivalent as running the released binary, both are versioned. Look at their [Dockerfile](https://github.com/golangci/golangci-lint/blob/master/Dockerfile), they just copy the binary over. So, wondering why running an image with the binary and not just the binary itself.

This is not a big issue, and more of a personal preference. So, I'm good either way.

**Comment by dbarrosop** [comment]
Because I am pinning the version in another PR:

https://github.com/nornir-automation/gornir/pull/21/files#diff-b67911656ef5d18c4ae36cb6741b7965R14

**Comment by nleiva** [comment]
Ok, I would leave the version as variable a the top of the file.

**Pull request merged**
