### PR TITLE
Add new builder pattern option (#7)

### PR DESCRIPTION
**Pull request by nleiva**
This is work in progress, another builder alternative.

- [x] Create Constructor/Build function
- [x] Update Examples
- [x] Add test cases
- [x] Update Readme file
- [ ] Revisit the current form/implementation of the pattern
- [ ] Create other concrete builder implementations?

### CODE REVIEW

**Comment by nleiva** [comment]
Examples in the test file for now:

```go
plugin := inv.FromYAML{HostsFile: tc.input}

builder := gornir.NewFromYAML()
original, err := builder.SetInventory(plugin).SetLogger(logger).Build()
```

And

```go
filtered, err := builder.SetInventory(plugin).SetLogger(logger).SetFilter(tc.filter).Build()
```

Not extremely happy the current form of this, just a first try as I get more familiar with the pattern.

**Comment by dbarrosop** [comment]
Both logrus and baloo (https://godoc.org/github.com/h2non/baloo) are quite big on this pattern.  Baloo is a great example, the only difference is that baloo modifies the original object which we don't want to here. But basically everything you need is to return a new object of the same type as the reciver:

``` golang
func (gr *Gornir) Filter(filterFunc FilterFunc) *Gornir {
      return &Gornir{
          logger: gr.logger,
          inventory: gr.Inventory.Filter(filterFunc),
      }
}

func (gr *Gornir) WithLogger(logger *Logger) *Gornir {
      return &Gornir{
          logger: logger,
          inventory: gr.Inventory,
      }
}

// etc...
```

Then in you code you can start just doing stuff like:

``` golang
results, err := gr.WithLogger(newLogger).Filter(someFilterfunc).Run(...)
```

You don't need to call `Build()` or even to assign the object to a variable, just modify it "on the fly" and run it. I can send a PR against this branch if you want to.

Also, I'd prefer not calling these `SetSomething` as usually "setters" modify the receiver.

**Comment by nleiva** [comment]
Oh, I see. So you don't actually want to follow the Builder pattern. Notice in the [example](https://github.com/tmrts/go-patterns/blob/master/creational/builder.md) you pointed out, the options return a Builder, not the object or interface we are building (Gornir in our case).

```go
type Builder interface {
    Color(Color) Builder
    Wheels(Wheels) Builder
    TopSpeed(Speed) Builder
    Build() Interface
}
```

I believe you just want to concatenate the options; which is OK but presents at least two problems off the top of my head:

1. The order matters, `gr.WithFilter(filter).WithInventory(plugin)` is different than `gr.WithInventory(plugin).WithFilter(filter)`. We can always document this, but as the number of options grow this must become an issue.

2. All option functions should return a `Gornir` and no `error`, just like `WithLogger` and `Filter` do today.  This means `WithInventory(plugin)` would need to ignore errors that the plugin would report if the source file doesn't exist or if something goes wrong when unmarshaling.

Feel free to make changes to either branch `constructor` or `constructor2`, or even create a new one. The idea is to be able to compare the alternatives and document the decisions we make, I'm good with any option.

**Comment by dbarrosop** [comment]
> So you don't actually want to follow the Builder pattern

it's the same pattern, the only difference is that they made an interface I guess to illustrate you can have a "car", a "bike", a "truck", etc... Notice that each method of the interface returns the interface as well so an implementation of the interface called "Car" would also return "Car".

> The order matters

That's going to matter no matter the implementation as the filter goes on top of the inventory.

> All option functions should return a Gornir and no error

Yeah, I think that's desirable, otherwise error handling becomes very difficult, so in your code you'd first get the object you want and then pass it, i.e.,:

``` golang
inv, err := inventory.FromYAML(...)
if err != nil {
    // handle error
}
logger, err := logger.Logrus(...)
if err != nil {
    // handle error
}
gr.WithInventory(inv).WithLogger(logger).Run(...)
```

I think this pattern is cleaner as I know what failed at each step, otherwise you'd have to somehow figure out if the io error you got was thrown by the inventory because it couldn't find the file or because you tried to log to a file and the destination directory didn't exist.

**Comment by nleiva** [comment]
Sounds good. Let me create yet another branch keep only the changes that are strictly necessary.

**Pull request closed without merging**
